{% set name = "opentelemetry-instrumentation-openai" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 8192e81bab0d35e6aa35271940ba4a147b1190e27c8d142489f0bda81baee5b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0

# Tests and import skipped, needs openai version 1.99.7, latest in the main channel is 1.77.0 
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry OpenAI instrumentation
  description: |
    This library allows tracing OpenAI prompts and completions sent with the official OpenAI library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - reachable_url
