{% set name = "opentelemetry-instrumentation-openai" %}
{% set version = "0.47.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: c9cddf1dee55a117fb44e0e46d39d9e80db2e67fdae9666394d7b8932dd53b91

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5.0
  run_constrained:
    - openai ==1.99.7

# Tests and import skipped, needs openai version 1.99.7, latest in the main channel is 1.77.0 
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry OpenAI instrumentation
  description: |
    This library allows tracing OpenAI prompts and completions sent with the official OpenAI library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
